spring:
    datasource:
        # h2 内存数据库 内存模式连接配置 库名：test_db
        url: jdbc:h2:mem:oldb
        # 驱动
        driver-class-name: org.h2.Driver
        # 用户名
        username: root
        # 密码
        password: 123456
        # 数据库创建脚本 （DDL）
        schema: classpath:db/schema.sql
        # 测试数据 （DDL）
        data: classpath:db/data.sql
    h2:
        console:
            enabled: true
            #访问路径上下文
            path: /h2-console
            settings:
                # 开启 h2 console 跟踪，方便调试，默认为false
                trace: true
                # 允许console远程访问，默认false
                web-allow-others: true
#日志
#logging:
#        level: debug